name: CI Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        version:
          - 1.42.0 # MSRV
          - stable
          - nightly

    name: ${{ matrix.version }} - x86_64-unknown-linux-gnu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Build
      run: cargo build --verbose
      
    # - name: Run tests
    #   run: cargo test --verbose
